### ISSUE TITLE
Add ESLint

### ISSUE THREAD

**Issue by believer** [opendevtools/supreme-ts#51]
Add ESLint config to `init` and `add` commands

**Comment by Pranay144** [comment]
Hi i am interested.
can you please guide me through this!

**Comment by believer** [comment]
@Pranay144 hi, great that you want to help out! What needs to be done is to add a basic `.eslintrc`, let's say only node development for now, as `.eslintrc.ejs` in the `templates` folder.

When you have a template, create a new function in the `tools/index.ts`. There other functions in that folder should be able to guide you. Then use that tool in `init.ts` and `add.ts` like the other tools are being used
